#!/bin/bash
# python3 filter_nccl.py traces/node0_cuda_gpu_trace_local_rank_0.csv traces/node0_cuda_gpu_trace_local_rank_0_filtered.csv
python3 filter_nccl.py traces/node2_cuda_gpu_trace_local_rank_0.csv traces/node2_cuda_gpu_trace_local_rank_0_filtered.csv